### ISSUE TITLE
Ripple.Binary.Codec Error

### ISSUE THREAD

**Issue by Platonenkov** [CASL-AE/xrpl.c#31]
occurs when trying to create an offer
```
Transaction is not valid. (Parameter 'tx')

Xrpl.Wallet.InvalidTxException: Transaction is not valid. (Parameter 'tx')
 ---> Ripple.Binary.Codec.Types.InvalidJsonException: Can't decode `TakerGets` from `0.82637`
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int64.Parse(String s)
   at Ripple.Binary.Codec.Types.NativeValue..ctor(String value) in D:\_MainData\XRPL\xrpl.CSharp\Xrpl.C\Ripple.Binary.Codec\Types\AmountValue.cs:line 262
   at Ripple.Binary.Codec.Types.AmountValue.FromString(String value, Boolean native) in D:\_MainData\XRPL\xrpl.CSharp\Xrpl.C\Ripple.Binary.Codec\Types\AmountValue.cs:line 18
   at Ripple.Binary.Codec.Types.Amount..ctor(String v, Currency c, AccountId i) in D:\_MainData\XRPL\xrpl.CSharp\Xrpl.C\Ripple.Binary.Codec\Types\Amount.cs:line 30
   at Ripple.Binary.Codec.Types.Amount.FromJson(JToken token) in D:\_MainData\XRPL\xrpl.CSharp\Xrpl.C\Ripple.Binary.Codec\Types\Amount.cs:line 70
   at Ripple.Binary.Codec.Types.StObject.FromJson(JToken token, Boolean strict) in D:\_MainData\XRPL\xrpl.CSharp\Xrpl.C\Ripple.Binary.Codec\Types\StObject.cs:line 126
   --- End of inner exception stack trace ---
   at Ripple.Binary.Codec.Types.StObject.FromJson(JToken token, Boolean strict) in D:\_MainData\XRPL\xrpl.CSharp\Xrpl.C\Ripple.Binary.Codec\Types\StObject.cs:line 133
   at Xrpl.Wallet.TxSigner.SignJson(JObject tx) in D:\_MainData\XRPL\xrpl.CSharp\Xrpl.C\Xrpl\Wallet\TxSigner.cs:line 39
   --- End of inner exception stack trace ---
   at Xrpl.Wallet.TxSigner.SignJson(JObject tx) in D:\_MainData\XRPL\xrpl.CSharp\Xrpl.C\Xrpl\Wallet\TxSigner.cs:line 42
```

I think that the Error is related to culture, but I cannot figure out what is happening here
![image](https://user-images.githubusercontent.com/44946855/187046236-e3fa59c2-0d27-41fd-8902-1ec22c81d034.png)
https://github.com/Transia-RnD/xrpl.c/blob/main/Xrpl.C/Ripple.Binary.Codec/Types/Amount.cs

I need your help

**Comment by Platonenkov** [comment]
https://github.com/Transia-RnD/xrpl.c/pull/32
