### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by bc-maker** [CASL-AE/xrpl.c#84]
I'm trying to sign a transaction but the EncodeForSigning method can't be found (I can see it in the object explorer) 

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.String Xrpl.BinaryCodec.XrplBinaryCodec.EncodeForSigning(System.Collections.Generic.Dictionary`2<System.String,System.Object>)'.
  Source=Xrpl
  StackTrace:
   at Xrpl.Wallet.XrplWallet.ComputeSignature(Dictionary`2 transaction, String privateKey, String signAs)
   at Xrpl.Wallet.XrplWallet.Sign(Dictionary`2 transaction, Boolean multisign, String signingFor)
   at Xrpl.Sugar.SubmitSugar.<GetSignedTx>d__2.MoveNext()
   at Xrpl.Sugar.SubmitSugar.<Submit>d__0.MoveNext()

Any advice of how to solve? 
Or anybody else having this issue?

**Comment by dangell7** [comment]
Can you show me your code?
